# 👋 Who We Are {transition="none-in slide-out"}

```{=html}
<style>
.panel {
  font-size: 0.6em;
  background: rgba(0.75, 0.75, 0.75, 0.1);
  padding: 1%;
  margin: 1%;
  border-radius: 0.5em;
  border-bottom: solid 0.2em rgba(1, 1, 1, 0.1);
}

.center {
  --r-heading-margin: auto;
  width: fit-content;
}

.person {
  font-weight: bold;
  font-size: 0.8em;
  margin: 1em 0 0.5em 0;
}

.person p {
  display: inline;
}

.person:before {
  display: inline;
  content: "👤 ";
}

.badge-pill {
  font-weight: bold;
  background: var(--r-link-color);
  color: white;
  border-radius: 1em;
  padding: 0 0.5em;
}
</style>
```

::: { style="font-size: 1.0em;" }
> The ***R Validation Hub*** is a collaboration to support the adoption of R
> within a biopharmaceutical regulatory setting ([pharmaR.org](https://www.pharmaR.org))
:::

* Grew out of **R/Pharma 2018**
* Led by participants from **~10 organizations**
* With frequent involvement from health authorities (primarily the FDA)
* And subscribers from **~60 organizations** spanning multiple industries



{{< include _r_consortium.qmd >}}



## 👷‍♂️ The R Validation Hub: What We Do {transition="slide-in slide-out"}

- Visit [pharmaR.org](https://www.pharmaR.org) to get involved!

### Products {.center}

::::: {.columns}
:::: {.column width="29%" .panel}
#### White Paper
Guidance on compliant use of R and management of packages
::::

:::: {.column width="29%" .panel}
#### Repositories

Building a public, validation-ready resource for R packages  

::: {.person}
Coline Zeballos
:::
::::

:::: {.column width="29%" .panel}
#### Communications

Connecting validation experts across the industry


::: {.person}
Jaxon Abercrombie, Anuja Das, Antal Martinecz
:::
::::
:::::

::::: {.columns}
:::: {.column width="29%" .panel}
#### [`{riskmetric}`](https://github.com/pharmaR/riskmetric)

Gather and report on risk heuristics to support validation decision-making

::: {.person}
Eric Milliman
:::
::::

:::: {.column width="29%" .panel}
#### [`{riskassessment}`](https://github.com/pharmaR/riskassessment)

A web interface to `{riskmetric}`, supporting review,
annotation and cataloging of decisions

::: {.person}
Aaron Clark, Jeff Thompson
:::
::::

:::: {.column width="29%" .panel}
#### [`{riskscore}`](https://github.com/pharmaR/riskscore)

An R data package capturing risk metrics across all of CRAN

::: {.person}
Aaron Clark
:::
::::
:::::

